spring.application.name=mindcare-diary

spring.ai.openai.api-key=${OPEN_AI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4
spring.ai.openai.embedding.options.model=text-embedding-3-small
spring.ai.vectorstore.oracle.index-type=hnsw
spring.ai.vectorstore.oracle.distance-type=cosine
spring.ai.vectorstore.oracle.dimensions=1536
spring.ai.vectorstore.oracle.initialize-schema=true

spring.main.allow-bean-definition-overriding=true

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/FREEPDB1
spring.datasource.username=MINDCARE
spring.datasource.password=${DB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.show-sql=true
spring.jpa.open-in-view=true

api.security.token.secret=12345678
