CREATE OR REPLACE FUNCTION MINDCARE.CARREGA_ULTIMOS_REGISTROS_DIARIOS (
    PACIENTE_NOME_USUARIO MINDCARE.USUARIO.NOME_USUARIO%TYPE
)
    RETURN SYS_REFCURSOR
    IS
    V_PACIENTE_ID NUMBER;
    V_RESULTADO SYS_REFCURSOR;
BEGIN

    SELECT ID
    INTO V_PACIENTE_ID
    FROM USUARIO
    WHERE NOME_USUARIO = PACIENTE_NOME_USUARIO;

    OPEN V_RESULTADO FOR
        SELECT *
        FROM REGISTRO_DIARIO
        WHERE PACIENTE_ID = V_PACIENTE_ID
          AND DATA_HORA_CRIACAO >=
              SYSTIMESTAMP - INTERVAL '7' DAY
        ORDER BY DATA_HORA_CRIACAO DESC;

    RETURN V_RESULTADO;

END CARREGA_ULTIMOS_REGISTROS_DIARIOS;
/