CREATE OR REPLACE PROCEDURE MINDCARE.REGISTRA_ALERTA_NIVEL_HUMOR_PACIENTE (
    PACIENTE_NOME_USUARIO IN VARCHAR2
)
AS
BEGIN
    UPDATE MINDCARE.USUARIO
    SET ESTADO_PACIENTE = 'ATENCAO'
    WHERE NOME_USUARIO = PACIENTE_NOME_USUARIO;
END REGISTRA_ALERTA_NIVEL_HUMOR_PACIENTE;
/